/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicreversi;

// import org.junit.jupiter.api.Test;
// import static org.junit.jupiter.api.Assertions.*;

// class AppTest {
//     @Test void appHasAGreeting() {
//         Main classUnderTest = new Main();
//     }
// }
