/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basicreversi;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class BoardTest {
    @Test void appHasAGreeting() {
        Board classUnderTest = new Board();
        assertNotNull(classUnderTest.getGreeting(), "app should have a greeting");
    }
}
